import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Organisms/Navbar/page";
import { ThemeProvider } from "next-themes";
import Providers from "./providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale}>
      <body className={`max-w-7xl bg-[#F4F4F4] mx-auto dark:bg-[#101010]`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
